### PR TITLE
Implement CakeEngine to use cake datasource. Fix some deprecations.

### LINKED ISSUE #18: is there any way to use cake datasource name to configure plugin?
According to the docs, the url could be the datasource name. The thing is that the only way I found to connect succesfully was using the mysql dsn. Is there any way to use the datasource name only?

### PR DESCRIPTION
**Pull request by ajibarra**
I have added a new engine (CakeEngine) to be able to use a cake datasource instead of the url. 

I have also increased phpunit version because unit tests were not running because of cake version and phpunit version. Additionally I fixed some deprecated notices but I am not sure if you were keeping them to be compatible with earlier 3.x versions..anyway let me know if you want to exclude anything.

Fixes #18

### CODE REVIEW

**Comment by josegonzalez** [comment]
Tests fail.

**Comment by ajibarra** [comment]
The issue was in travis file. I removed php 5.5 and fixed phpunit command to use the one from composer. PHPCS will keep reporting an error because of migrations namespace.

**Comment by josegonzalez** [comment]
Can you add migrations to the ignore path for phpcs?

**Comment by ajibarra** [comment]
It was already but the command was wrong. Already fixed and fixed phpunit.xml as well..we should be fine now

**Comment by steinkel** [comment]
@josegonzalez I've added a migration to match changes done here https://github.com/josegonzalez/php-queuesadilla/pull/73 and allow using FIFO strategy for jobs

**Comment by ajibarra** [comment]
Anything pending here? @josegonzalez

**Pull request merged**
