### PR TITLE
Added maxIterations 

### PR DESCRIPTION
**Pull request by nabilacoutinho**
Passing maxIterations configured to worker

### CODE REVIEW

**Comment by cleptric** [comment]
In what kind of scenario would you find such a feature useful? Also, tests are missing 😄

**Comment by nabilacoutinho** [comment]
Oh, tests....  =D
I need to configure it in my chron job. On my application we expect to interact a maximum times before quit worker.

**Comment by cleptric** [comment]
@nabilacoutinho I'm sorry, I mixed this up with the other repo (https://github.com/josegonzalez/php-queuesadilla)
As this option is already present in the sequential worker, all is good 😄

**Comment by nabilacoutinho** [comment]
OK! Thanks guys!

**Pull request merged**
